on:
  workflow_call:
    inputs:
      AZURE_FUNCTIONAPP_PACKAGE_PATH:
        required: true
        type: string
      CONFIGURATION:
        required: true
        type: string
      DOTNET_CORE_VERSION:
        required: true
        type: string
      WORKING_DIRECTORY:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ inputs.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ inputs.WORKING_DIRECTORY }}" --configuration ${{ inputs.CONFIGURATION }} --no-restore
    - name: Publish
      run: dotnet publish "${{ inputs.WORKING_DIRECTORY }}" --configuration ${{ inputs.CONFIGURATION }} --no-build --output "${{ inputs.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: functionapp
        path: ${{ inputs.AZURE_FUNCTIONAPP_PACKAGE_PATH }}