on:
  workflow_call:
    inputs:
      AZURE_FUNCTIONAPP_PACKAGE_PATH:
        required: true
        type: string
      AZURE_FUNCTIONAPP_NAME:
        required: true
        type: string
    secrets:
      everyeyefeeds_64FD:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: functionapp
        path: ${{ inputs.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ inputs.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.everyeyefeeds_64FD }}
        package: ${{ inputs.AZURE_FUNCTIONAPP_PACKAGE_PATH }}