on:
  workflow_call:
    secrets:
      everyeyefeeds_64FD:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Set environment variables
      uses: ./.github/actions/set-env-variables
      with:
        varFilePath: ./.github/default-variables.env
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: functionapp
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.everyeyefeeds_64FD }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
