on:
  workflow_call:
    # env:
    #   AZURE_FUNCTIONAPP_PACKAGE_PATH:
    #     required: true
    #     type: string
    #   AZURE_FUNCTIONAPP_NAME:
    #     required: true
    #     type: string
    secrets:
      everyeyefeeds_64FD:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set environment variables
      uses: ../actions/set-env-variables.yml
      with:
        varFilePath: ../default-variables.env
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: functionapp
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.everyeyefeeds_64FD }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}