name: Build and deploy

on:
  push:
    branches:
    - master

jobs:
  build-project:
    uses: ./.github/workflows/build-project.yml
    with:
      is-pr: false
  deploy-func:
    uses: ./.github/workflows/deploy-func.yml
    needs: build-project
    secrets: inherit
