name: Build and deploy
on:
  push:
    branches:
    - master
jobs:
  build:
    uses: ./.github/workflows/build-and-publish.yml
  deploy:
    uses: ./.github/workflows/deploy-func.yml
    secrets: inherit
